### ISSUE TITLE
what are the changes if we use this in java

### ISSUE THREAD

**Issue by jitanshu** [shetmobile/MeowBottomNavigation#10]

**Comment by Marcosmaliki** [comment]
Switch to kotlin, it's easy to grasp if you can vode in java already

**Comment by shetmobile** [comment]
sorry. i will add java tutorial in ReadMe.

**Comment by shetmobile** [comment]
sorry. i will add java tutorial in ReadMe.

**Comment by shetmobile** [comment]
I updated ReadMe.md file. Just check it.
