### ISSUE TITLE
Selected button background

### ISSUE THREAD

**Issue by arbalali** [shetmobile/MeowBottomNavigation#11]
Hello Hamidreza.
I'm using your awesome BottomNavigation.
Now, I want to set background color for selected button.
Is this possible? Can you help me on this?

tnx (:

**Comment by ysmaiylbokeikhan** [comment]
Hello Hamidreza.
It will so great if it will possible to change selected item background color!

**Comment by arbalali** [comment]
https://github.com/shetmobile/MeowBottomNavigation/issues/11#issue-436598529

??

**Comment by shetmobile** [comment]
i will add it soon

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
