### ISSUE TITLE
How to use it in Java?

### ISSUE THREAD

**Issue by b7ca6q** [shetmobile/MeowBottomNavigation#12]
Actually I haven't used kotlin till yet and doesn't ever wanna bother but, you did such a great job so I wanna implement it in my existing project.

Wann to know how to add nav menu items in java and call it from Java code.

Thanx in Advance

**Comment by Marcosmaliki** [comment]
I'm using this in a java project as the main activity for all my fragments. The main activity is in kotlin but everything else is java. This two languages are interoperable

**Comment by Shruthyshanthraj** [comment]
Im trying use it use it for java project. I am unable to implement listners can you please help me out.

**Comment by noyanebi** [comment]
implement with java   

 bottom_navigation.add(new MeowBottomNavigation.Model(1, R.drawable.arrow));
        bottom_navigation.add(new MeowBottomNavigation.Model(2, R.drawable.bookmark));
       

bottom_navigation.setOnClickMenuListener(model -> {
            if (model.getId() == 1)
                vpg_wall.setCurrentItem(1);
            else if (model.getId() == 2)
                vpg_wall.setCurrentItem(2);
       
            return null;
        });

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
