### ISSUE TITLE
How Reset Navigation Count

### ISSUE THREAD

**Issue by salahturkmen** [shetmobile/MeowBottomNavigation#13]
after set not count how reset it

**Comment by Tsabary** [comment]
Same issue. When the count is 0 the count icon should just disappear, but it is still present.

**Comment by Tsabary** [comment]
Ok, to anyone else wondering how to reset the count so the count icon doesn't show, simply pass to the setCount method "empty" as the count.

                    bottomNavigation.setCount(2, "empty")

**Comment by shetmobile** [comment]
i will add reset function for cells.

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
