### ISSUE TITLE
typealias setOnClickMenuListener not accessible form Java

### ISSUE THREAD

**Issue by Duna** [shetmobile/MeowBottomNavigation#15]
Can you drop typealias and use an interface from setOnClickMenuListener and setOnShowListener in order to make your library compatible with Java?

**Comment by hrabiian2** [comment]
> 
> 
> Can you drop typealias and use an interface from setOnClickMenuListener and setOnShowListener in order to make your library compatible with Java?

you can use this code in java:

bottomNavigation.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
            @Override
            public Unit invoke(MeowBottomNavigation.Model model) {
                switch (model.getId()){
                    case 1:
                        bottomNavigation.setBackgroundResource(R.color.purplebg);
                        break;

                    case 2:
                        bottomNavigation.setBackgroundResource(R.color.crimsonbg);
                        break;

                    case 3:
                        bottomNavigation.setBackgroundResource(R.color.greenbg);
                        break;

                    case 4:
                        bottomNavigation.setBackgroundResource(R.color.bluebg);
                        break;

                    case 5:
                        bottomNavigation.setBackgroundResource(R.color.yellowbg);
                        break;
                }
                return null;
            }

**Comment by technohowl** [comment]
> > Can you drop typealias and use an interface from setOnClickMenuListener and setOnShowListener in order to make your library compatible with Java?
> 
> you can use this code in java:
> 
> bottomNavigation.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
> @override
> public Unit invoke(MeowBottomNavigation.Model model) {
> switch (model.getId()){
> case 1:
> bottomNavigation.setBackgroundResource(R.color.purplebg);
> break;
> 
> ```
>                 case 2:
>                     bottomNavigation.setBackgroundResource(R.color.crimsonbg);
>                     break;
> 
>                 case 3:
>                     bottomNavigation.setBackgroundResource(R.color.greenbg);
>                     break;
> 
>                 case 4:
>                     bottomNavigation.setBackgroundResource(R.color.bluebg);
>                     break;
> 
>                 case 5:
>                     bottomNavigation.setBackgroundResource(R.color.yellowbg);
>                     break;
>             }
>             return null;
>         }
> ```

It doesn't work.

**Comment by borzadaran** [comment]
**Step 1**: Configure your Kotlin with Java ( in Android Studio)

` Tools -> Kotlin -> Configure Kotlin with Java`
**Step 2**: Use the following code: 
```
        meowBottomNavigation.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
            @Override
            public Unit invoke(MeowBottomNavigation.Model model) {
                if (model.getId() == 1)
                    meowBottomNavigation.setBackgroundResource(R.color.white);
                else
                    meowBottomNavigation.setBackgroundResource(R.color.red);
                return null;
            }
        });
```

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.

**Comment by Mohsen-Nejati** [comment]
> 
> 
> **Step 1**: Configure your Kotlin in Project ( in Android Studio)
> 
> > Tools > Kotlin > Configure Kotlin in Project > Android with Gradle
> 
> **Step 2**: Use the following code:
> 
> ```
>         meowBottomNavigation.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
>             @Override
>             public Unit invoke(MeowBottomNavigation.Model model) {
>                 if (model.getId() == 1)
>                     meowBottomNavigation.setBackgroundResource(R.color.white);
>                 else
>                     meowBottomNavigation.setBackgroundResource(R.color.red);
>                 return null;
>             }
>         });
> ```


thank you a lot ... you save me for real :)

**Comment by shetmobile** [comment]
> > **Step 1**: Configure your Kotlin in Project ( in Android Studio)
> > > Tools > Kotlin > Configure Kotlin in Project > Android with Gradle
> > 
> > 
> > **Step 2**: Use the following code:
> > ```
> >         meowBottomNavigation.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
> >             @Override
> >             public Unit invoke(MeowBottomNavigation.Model model) {
> >                 if (model.getId() == 1)
> >                     meowBottomNavigation.setBackgroundResource(R.color.white);
> >                 else
> >                     meowBottomNavigation.setBackgroundResource(R.color.red);
> >                 return null;
> >             }
> >         });
> > ```
> 
> thank you a lot ... you save me for real :)

This is one solution
