### ISSUE TITLE
Notification badge is too close to the top of the bar

### ISSUE THREAD

**Issue by Tsabary** [shetmobile/MeowBottomNavigation#16]
The circle showing the notification count has no space at all from the top of the bar itself. Doesn't look aesthetic. Is there a way to create a gap without copying the whole project? It could use like a 2dp margin

**Comment by pranishres** [comment]
Have you found out the solution?

**Comment by shetmobile** [comment]
can you send screenshot ?
what is the device?
@Tsabary
