### ISSUE TITLE
How to reset item selection 

### ISSUE THREAD

**Issue by surabhimindinfo** [shetmobile/MeowBottomNavigation#17]
How to remove item selection from bottom navigation.

**Comment by PrateekJain210493** [comment]
Did you found any solution for this?

**Comment by surabhimindinfo** [comment]
Yes, i found the solution . use bottomNavigation.show(item_id) to show the selected item and open dedicated fragment for that item and it'll automatically remove the previous selection.

**Comment by ehsansouri23** [comment]
I found a way. for reset item selection you can use show(-1)

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
