### ISSUE TITLE
Issue when declare Listener in OnCreate

### ISSUE THREAD

**Issue by Gamis214** [shetmobile/MeowBottomNavigation#19]
I found this issue: 

when i create the class first to do is init the component like this:

`bottomMenu!!.add(MeowBottomNavigation.Model(1, R.drawable.ic_facebook))
        bottomMenu!!.add(MeowBottomNavigation.Model(2, R.drawable.ic_twitter))
        bottomMenu!!.add(MeowBottomNavigation.Model(3, R.drawable.ic_instagram))
        bottomMenu!!.setOnShowListener { when(it.id){
            OPC1 -> onClickMenu(it.id)
            OPC2 -> onClickMenu(it.id)
            OPC3 -> onClickMenu(it.id)
            else -> ""
        } }
        bottomMenu!!.show(1, true)`

But the issue begin when the app is running the OnClickMenu() in OPC1 execute 5 times... why ??

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
