### ISSUE TITLE
Notification Badge

### ISSUE THREAD

**Issue by Isma3ilMohamed** [shetmobile/MeowBottomNavigation#2]
how to add notification badge to each menu item ??

**Comment by shetmobile** [comment]
use setCount() funtion

**Comment by Isma3ilMohamed** [comment]
opps sorry for that but i didn't see it in docs
btw
can i use it in main thread ??

**Comment by behiunforgiven** [comment]
and you can remove it by
```
navigation.getCellById(ID_PROFILE)?.count = MeowBottomNavigationCell.EMPTY_VALUE
```

**Comment by shetmobile** [comment]
@Isma3ilMohamed you can use it in main thread
