### ISSUE TITLE
How to set Default item selected ?

### ISSUE THREAD

**Issue by cloner7575** [shetmobile/MeowBottomNavigation#20]

**Comment by MidoHosny** [comment]
yes you can use show method like this

        val ID_HOME = 1
        bottomNavigation.add(MeowBottomNavigation.Model(ID_HOME, R.drawable.ic_home))
        bottomNavigation.show(ID_HOME)

**Comment by happilywaheed** [comment]
how to set clicklistner in java

**Comment by renaldi2108** [comment]
> how to set clicklistner in java

You can try it like this, correction if I have errors:

```
        MeowBottomNavigation haha = findViewById(R.id.mbn_navigation);
        haha.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
            @Override
            public Unit invoke(MeowBottomNavigation.Model model) {
                // TODO: YOUR INSTRUCTION
                return null;
            }
        });
```

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
