### ISSUE TITLE
How to change background color to transparent

### ISSUE THREAD

**Issue by naufalprakoso** [shetmobile/MeowBottomNavigation#21]
<img width="302" alt="Screen Shot 2019-09-03 at 18 14 33" src="https://user-images.githubusercontent.com/15768474/64168884-b9317600-ce76-11e9-874c-fc00b3c8b44f.png">

![Screen Shot 2019-09-03 at 18 16 52](https://user-images.githubusercontent.com/15768474/64169048-0c0b2d80-ce77-11e9-8fb7-c7f1caaae96c.png)

![Screen Shot 2019-09-03 at 18 16 59](https://user-images.githubusercontent.com/15768474/64169057-1299a500-ce77-11e9-9b57-0994d8885b27.png)

I want to make MeowBottomNavigation background color to transparent

**Comment by baudelioandalon** [comment]
Works?

**Comment by vedprakashwagh** [comment]
@naufalprakoso You just have to set

        android:background="@android:color/transparent"

to MeowBottomNavigation and make sure that the view below the meowbottomnavigation covers the whole screen.
