### ISSUE TITLE
How to use label for each tab

### ISSUE THREAD

**Issue by deepakrana0011** [shetmobile/MeowBottomNavigation#22]
I want to use label for each tab , how can i achieve that?

**Comment by pranishres** [comment]
Have you found out the solution? I am also seeking to add labels to each menu item

**Comment by darpal1995** [comment]
well.. i was trying to find a solution for that in the library. But couldnt see anything. In Worst case scenario might have to just go with adding textviews in the view.

**Comment by shetmobile** [comment]
sorry, we don't have this feature
