### ISSUE TITLE
setOnShowListener issue

### ISSUE THREAD

**Issue by yeagneshabgard** [shetmobile/MeowBottomNavigation#24]
I have used this library and set its onShowLisener and its OnClickMenuListener it works for many times but for sometimes when one item selected it does not work and by second or third click it'll work.
thanks

**Comment by shetmobile** [comment]
please send more info like codes and device

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
