### ISSUE TITLE
Selected Icon not showing

### ISSUE THREAD

**Issue by akankshapaul048** [shetmobile/MeowBottomNavigation#25]
The selected icon becomes invisible
Device- Realme 2 Pro
OS - Pie

![image](https://user-images.githubusercontent.com/35328127/66107229-5948ff00-e5dd-11e9-8db7-071aa52eaac4.png)

**Comment by nishchalraj** [comment]
can you show the logs. May be it's the problem with the device. Have you checked in the emulator ?

**Comment by shetmobile** [comment]
please send your codes and device info

**Comment by akankshapaul048** [comment]
I got the issue and resolved it. 
There was problem with elevation and it is overlapping the top view.
