### ISSUE TITLE
How to use navigation graph?

### ISSUE THREAD

**Issue by Djafar-AML** [shetmobile/MeowBottomNavigation#26]
Hi there, I just wanna use this just like android default bottomNavigation in my code:
------------------xml-------------
    <com.google.android.material.bottomnavigation.BottomNavigationView
                android:id="@+id/bottom_nav"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                app:labelVisibilityMode="labeled"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:menu="@menu/bottom_nav" />

------------------------activity--------------
navController = Navigation.findNavController(this , id.home_nav_host_fragment)

binding.bottomNav.setupWithNavController(navController)

NavigationUI.setupActionBarWithNavController(this , navController)

**Comment by toshiro97** [comment]
because it extend framelayout so you can't use setupActionBarWithNavController
