### ISSUE TITLE
Remove count badge

### ISSUE THREAD

**Issue by innoflash** [shetmobile/MeowBottomNavigation#28]
Say i have a count of 0 (zero) how do i remove the badge from the icon?

**Comment by gonzalomonzon02** [comment]
Hi, I solved this with the next line:
       ` bottomNavigation.setCount(TAB_HOME, MeowBottomNavigationCell.EMPTY_VALUE)`
If you need handle this when the user clicked on specific tab, you use setOnShowListener as follow:
```
bottomNavigation?.setOnShowListener {
            if (it.id == TAB_HOME) {
                bottomNavigation.setCount(TAB_HOME, MeowBottomNavigationCell.EMPTY_VALUE)
            }
        }
```

**Comment by innoflash** [comment]
> Hi, I solved this with the next line:
> ` bottomNavigation.setCount(TAB_HOME, MeowBottomNavigationCell.EMPTY_VALUE)`
> If you need handle this when the user clicked on specific tab, you use setOnShowListener as follow:
> 
> ```
> bottomNavigation?.setOnShowListener {
>             if (it.id == TAB_HOME) {
>                 bottomNavigation.setCount(TAB_HOME, MeowBottomNavigationCell.EMPTY_VALUE)
>             }
>         }
> ```

Thanks buddy, i will definitely check it out

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
