### ISSUE TITLE
Keypad closes as soon as editText is focused in fragment

### ISSUE THREAD

**Issue by rahulas** [shetmobile/MeowBottomNavigation#3]
UI & animations are damn good in this library. Coming to the issue, I'm calling a fragment when one of the menu items are clicked and Keypad keeps closes as soon as editText is focused in that fragment. I checked it many a times but, result is same. Can you help me in fixing this please?

**Comment by shetmobile** [comment]
thank, i will check it

**Comment by shetmobile** [comment]
I tested and there is not bug. can you send your code?

**Comment by rahulas** [comment]
`package rahul.user.verification

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.fragment.app.Fragment
import com.etebarian.meowbottomnavigation.MeowBottomNavigation
import kotlinx.android.synthetic.main.activity_main2.*

class Main2Activity : AppCompatActivity() {

    companion object {
        private const val ID_VERIFY_USER = 1
        private const val ID_USERS = 2
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main2)

        bottomNavigation.add(MeowBottomNavigation.Model(ID_VERIFY_USER, R.drawable.ic_add_user))
        bottomNavigation.add(MeowBottomNavigation.Model(ID_USERS, R.drawable.ic_users))

        bottomNavigation.show(ID_USERS, true)

        bottomNavigation.setOnShowListener {
            when (it.id) {
                ID_VERIFY_USER -> {
                    loadFragment(AddVerifyUserFragment(), AddVerifyUserFragment.TAG)
                }
                ID_USERS -> {
                    loadFragment(UsersListFragment(), UsersListFragment.TAG)
                }
                else -> {

                }
            }
        }

        bottomNavigation.setOnClickMenuListener {
            when (it.id) {
                ID_VERIFY_USER -> {
                    loadFragment(AddVerifyUserFragment(), AddVerifyUserFragment.TAG)
                }
                ID_USERS -> {
                    loadFragment(UsersListFragment(), UsersListFragment.TAG)
                }
                else -> {

                }
            }
        }
    }


    private fun loadFragment(fragment: Fragment, tag: String) {
        supportFragmentManager
                .beginTransaction()
                .replace(R.id.fragment_container, fragment, tag)
                .commit()
    }
}
`

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorPrimary"
    android:orientation="vertical"
    tools:context=".Main2Activity">

    <RelativeLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/bottomNavigation" />

    <com.etebarian.meowbottomnavigation.MeowBottomNavigation
        android:id="@+id/bottomNavigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        app:mbn_backgroundBottomColor="#ffffff"
        app:mbn_countBackgroundColor="#ff6f00"
        app:mbn_countTextColor="#ffffff"
        app:mbn_defaultIconColor="#90a4ae"
        app:mbn_rippleColor="#2f424242"
        app:mbn_selectedIconColor="#3c415e"
        app:mbn_shadowColor="#1f212121" />
</FrameLayout>`



`package rahul.user.verification;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.fragment.app.Fragment;

public class UsersListFragment extends Fragment {

    public static final String TAG = UsersListFragment.class.getName();
    private View v;

    public UsersListFragment() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        v = inflater.inflate(R.layout.fragment_users_list, container, false);
        return v;
    }
}
`

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".UsersListFragment">

    
    <androidx.appcompat.widget.AppCompatEditText
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="@string/hello_blank_fragment" />

</FrameLayout>`

**Comment by rahulas** [comment]
Did you try out edittext in a fragment which opens on menu item selected?

**Comment by rahulas** [comment]
Got it solved.. calling fragment on both menu click and show listener dismissing the keypad. Thanks for the library.

**Comment by rezaghahremani77** [comment]
Hii Mr rahulas. I have this problem too. Could yo help me?

**Comment by rezaghahremani77** [comment]
> Got it solved.. calling fragment on both menu click and show listener dismissing the keypad. Thanks for the library.

Help me, i have this problem too
