### ISSUE TITLE
Show Fragment in setOnClickMenuListener 

### ISSUE THREAD

**Issue by Sanaebadi97** [shetmobile/MeowBottomNavigation#32]
Hi, I want to show fragments in MVVM arc, but  I get crashes, anybody can handle fragments with this library?

**Comment by renaldi2108** [comment]
> Hi, I want to show fragments in MVVM arc, but I get crashes, anybody can handle fragments with this library?

I haven't tried it in MVVM arc, but you can try it like this:

```
mbn_navigation.setOnClickMenuListener {
            when(it.id) {
                HOME -> addFragment(HomeFragment.newInstance()) // TODO: ADD FRAGMENT
                AR -> addFragment(ARFragment.newInstance()) // TODO: ADD FRAGMENT
                SETTING -> addFragment(SettingFragment.newInstance()) // TODO: ADD FRAGMENT
            }
        }
```

**Comment by ahmedkabut** [comment]
hi pro ,please if you dont mind . iam trying for 2 week in this library .

i want when click open view in the same screen 
notes:- and i dont how to do fragment

plesssssssssss

**Comment by ahmedkabut** [comment]
> > Hi, I want to show fragments in MVVM arc, but I get crashes, anybody can handle fragments with this library?
> 
> I haven't tried it in MVVM arc, but you can try it like this:
> 
> ```
> mbn_navigation.setOnClickMenuListener {
>             when(it.id) {
>                 HOME -> addFragment(HomeFragment.newInstance()) // TODO: ADD FRAGMENT
>                 AR -> addFragment(ARFragment.newInstance()) // TODO: ADD FRAGMENT
>                 SETTING -> addFragment(SettingFragment.newInstance()) // TODO: ADD FRAGMENT
>             }
>         }
> ```
> 
> hopefully can help you :)

pro in the same screen how 
plesssss

**Comment by shetmobile** [comment]
please speak in your language and i will translated it

**Comment by banjodayo39** [comment]
> > > Hi, I want to show fragments in MVVM arc, but I get crashes, anybody can handle fragments with this library?
> > 
> > 
> > I haven't tried it in MVVM arc, but you can try it like this:
> > ```
> > mbn_navigation.setOnClickMenuListener {
> >             when(it.id) {
> >                 HOME -> addFragment(HomeFragment.newInstance()) // TODO: ADD FRAGMENT
> >                 AR -> addFragment(ARFragment.newInstance()) // TODO: ADD FRAGMENT
> >                 SETTING -> addFragment(SettingFragment.newInstance()) // TODO: ADD FRAGMENT
> >             }
> >         }
> > ```
> > 
> > 
> > hopefully can help you :)
> 
> pro in the same screen how
> plesssss

   private fun initNavigationCick() {
        mbn_navigation.setOnClickMenuListener { p1 ->
            val i = p1.id
            when (i) {
            // int number tally with the number you use to set the image, the first item
                1 -> {
                    // to do 
                }
                2 -> {
                    // to do
                }
                3 -> {
                  // to do
                }
                4 -> {
                    // to do 
                }
            }
            Unit
        }
    }

**Comment by shetmobile** [comment]
I updated ReadMe.md file. Just check it.
