### ISSUE TITLE
     Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.etebarian.meowbottomnavigation.MeowBottomNavigation

### ISSUE THREAD

**Issue by alfayedoficial** [shetmobile/MeowBottomNavigation#34]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alialfayed.facerecognition/com.alialfayed.facerecognition.view.activity.HomeActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.etebarian.meowbottomnavigation.MeowBottomNavigation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.etebarian.meowbottomnavigation.MeowBottomNavigation
     Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.etebarian.meowbottomnavigation.MeowBottomNavigation

**Comment by Meglali20** [comment]
I have the same problem, any solution ?

**Comment by SimpleappRed** [comment]
I have the same problem :(

**Comment by SimpleappRed** [comment]
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alialfayed.facerecognition/com.alialfayed.facerecognition.view.activity.HomeActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.etebarian.meowbottomnavigation.MeowBottomNavigation
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
> at android.app.ActivityThread.-wrap11(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
> at android.os.Handler.dispatchMessage(Handler.java:105)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6541)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
> Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.etebarian.meowbottomnavigation.MeowBottomNavigation
> Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.etebarian.meowbottomnavigation.MeowBottomNavigation

in my case this line caused an error since I don't have this font, it's just my carelessness:
app:mbn_countTypeface="fonts/SourceSansPro-Regular.ttf"

**Comment by shetmobile** [comment]
please give more info from your activity and device

**Comment by alfayedoficial** [comment]
when add 
 <com.etebarian.meowbottomnavigation.MeowBottomNavigation
		  android:layout_width="match_parent"
		  android:layout_height="wrap_content"
		  android:id="@+id/bottomNavigation"
		  app:layout_constraintBottom_toBottomOf="parent"
		  app:layout_constraintEnd_toEndOf="parent"
		  app:layout_constraintStart_toStartOf="parent"
		  app:mbn_backgroundBottomColor="#ffffff"
		  app:mbn_circleColor="#ffffff"
		  app:mbn_countBackgroundColor="#ff6f00"
		  app:mbn_countTextColor="#ffffff"
		  app:mbn_countTypeface="fonts/SourceSansPro-Regular.ttf"
		  app:mbn_defaultIconColor="#90a4ae"
		  app:mbn_rippleColor="#2f424242"
		  app:mbn_selectedIconColor="#3c415e"
		  app:mbn_shadowColor="#1f212121" />

to activity give me this error

**Comment by alfayedoficial** [comment]
hey , i found error when add app:mbn_countTypeface="fonts/SourceSansPro-Regular.ttf"
give error but if i delete "app:mbn_countTypeface="fonts/SourceSansPro-Regular.ttf"
" error was gone

**Comment by oneHamidreza** [comment]
just change it with your font path in assets.
