### ISSUE TITLE
Reselect listener

### ISSUE THREAD

**Issue by gonzalomonzon02** [shetmobile/MeowBottomNavigation#39]
Hi, how to set reselect listener?

**Comment by shetmobile** [comment]
Write again or put in a function. It's easy.

**Comment by gonzalomonzon02** [comment]
> Write again or put in a function. It's easy.

Yes, but I don't know what the method is called when the Tab is selected again

**Comment by shetmobile** [comment]
we don't have this feature yet. i will add this feature.

**Comment by gonzalomonzon02** [comment]
> we don't have this feature yet. i will add this feature.

Great, thanks!

**Comment by shetmobile** [comment]
Added. Check Latest Version : 1.2.0.
