### ISSUE TITLE
From Kotlin to Java

### ISSUE THREAD

**Issue by rakibhasan1030** [shetmobile/MeowBottomNavigation#41]
Please, upload a full source of java for this project. Many of us who code in java can't understand the kotlin code, there is not enough source to convert kotlin to java. The ByteCode are also so confusing. Please, update it for java also.

**Comment by rakibhasan1030** [comment]
I can't convert your MyContextWrapper.kt file to java, please give a response bro...

**Comment by shetmobile** [comment]
Hi @rakibhasan1030.
I tested this library in a java library without any problem. Did you try version 1.2.0?

**Comment by shetmobile** [comment]
Hi @rakibhasan1030.
I tested this library in a java library without any problem. Did you try version 1.2.0?

**Comment by gordonfreemanix** [comment]
@shetmobile Java is not working please help. The project, android studio freezes. and the letter c in the class logos goes. please do for JAVA

**Comment by shetmobile** [comment]
Ok . I will check it.

**Comment by shetmobile** [comment]
Check this link: https://github.com/shetmobile/MeowBottomNavigationJava
