### ISSUE TITLE
How to Use listeners in Java

### ISSUE THREAD

**Issue by Rudra-n-khatri** [shetmobile/MeowBottomNavigation#8]
How can i use this in Java ? 
i tried to use it but I couldn't find the usage of listeners here.

**Comment by imfullstackdeveloper** [comment]
meowBottomNavigation.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
            @Override
            public Unit invoke(MeowBottomNavigation.Model model) {
                if (model.getId() == 1) {
                    visibleFragment(new FragmentBus());
                } else if (model.getId() == 2) {
                    visibleFragment(new FragmentSetting());
                }
                return null;
            }
        });

**Comment by imfullstackdeveloper** [comment]
MeowBottomNavigation meowBottomNavigation = findViewById(R.id.meowBottomNavigation);
        meowBottomNavigation.add(new MeowBottomNavigation.Model(1, R.drawable.vector_bus));
        meowBottomNavigation.add(new MeowBottomNavigation.Model(2, R.drawable.vector_setting));
        meowBottomNavigation.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
            @Override
            public Unit invoke(MeowBottomNavigation.Model model) {
                if (model.getId() == 1) {
                    visibleFragment(new FragmentBus());
                } else if (model.getId() == 2) {
                    visibleFragment(new FragmentSetting());
                }
                return null;
            }
        });

**Comment by innoflash** [comment]
> ```
>     MeowBottomNavigation meowBottomNavigation = findViewById(R.id.meowBottomNavigation);
>     meowBottomNavigation.add(new MeowBottomNavigation.Model(1, R.drawable.vector_bus));
>     meowBottomNavigation.add(new MeowBottomNavigation.Model(2, R.drawable.vector_setting));
>     meowBottomNavigation.setOnClickMenuListener(new Function1<MeowBottomNavigation.Model, Unit>() {
>         @Override
>         public Unit invoke(MeowBottomNavigation.Model model) {
>             if (model.getId() == 1) {
>                 visibleFragment(new FragmentBus());
>             } else if (model.getId() == 2) {
>                 visibleFragment(new FragmentSetting());
>             }
>             return null;
>         }
>     });
> ```

i tried that but the `new Function1<MeowBottomNavigation.Model, Unit>()` is not recognized by android Studio

**Comment by innoflash** [comment]
> How can i use this in Java ?
> i tried to use it but I couldn't find the usage of listeners here.

I found that i had not enabled Kotlin for this project so i found an answer here 
[https://stackoverflow.com/questions/35161913/kotlin-cannot-access-kotlin-jvm-functions-function1-when-calling-kotlin-function/35345086](url)

My problem got fixed when I configured Kotlin compiler and runtime for my Java module with the latest stable version (currently 1.3.30)

Just go to **Tools > Kotlin > Configure Kotlin in Project > Android with Gradle** and choose your Java module with Single module radio button selected then select your version and **OK**.

**Comment by shetmobile** [comment]
sorry. i will add java tutorial in ReadMe.

**Comment by shetmobile** [comment]
I updated the library with some improvements and bug fixes with ReadMe.md. Just check it.
