### ISSUE TITLE
consider migrating to jitpack or maven central

### ISSUE THREAD

**Issue by yamin8000** [shetmobile/MeowBottomNavigation#83]
@oneHamidreza 
jCenter is currently deprecated and artifacts can only be downloaded till 2022-02-01, consider migrating to jitpack or maven central.
[more info here](https://developer.android.com/studio/build/jcenter-migration)

**Comment by gauravmandall** [comment]
Same Issue

**Comment by Chronostyle** [comment]
up, i still needed this library, it's still usefull, please migrate it
